---
- block:
  - name: Export shared directories
    nfs_exports:
      name: "{{ item.src }} Share"
      action: add
      path: "{{ item.src }}"
      clients: "*"
      read_only: false
      update: true
      root_squash: false
    with_items: "{{ nfs_exports }}"
    become: yes

  # Open the nfs tcp port in the firewall so machines can access our exports.
  - include_tasks: "{{ playbook_dir }}/library/firewall_port.yml"
    vars:
      port: 2049/tcp
      open: true

  - name: Start NFS Service
    systemd:
      name: nfs-server
      state: restarted
      enabled: true
    become: yes
