---
- block:
  # We need SELinux disabled for any systems where we'll use home directories
  # (in particular, SSH files) in NFS.
  - name: Disable SELinux
    selinux:
      state: disabled
    register: selinux_result
    become: yes

  - name: Restart system to apply SELinux changes
    include_tasks: "{{ playbook_dir }}/library/restart_system.yml"
    when: selinux_result.reboot_required
  when: not is_infrastructure
