---
_base_selection:
  distribution: "{{ ansible_distribution + ansible_distribution_version }}"
  architecture: "{{ ansible_machine }}"
  environment:
    - "{{ python_alternative }}"

_packages:
  ##########################################################################
  # Common to all distributions.
  ##########################################################################
  - common:
    - athinfo
    - athinfod
    - authselect
    - autofs
    - bind-utils
    - clang
    - emacs
    - git
    - lsof
    # OPS-13462: need libblkid-devel to compile vdoformat
    - libblkid-devel
    # OPS-13133: lz4-devel to replace our own copy
    - lz4-devel
    # Only needed until checkServer is weaned off of ifconfig.
    - net-tools
    - nfs-utils
    # OPS-15128: need Data::Compare for all tests
    # #XXX: We really do.  But yet it's not listed here?
    - perl-Permabit-Configured
    - rsync
    - scam
    - smartmontools
    - sssd
    - tcsh
    - tmux
    - traceroute
    - xauth

  ##########################################################################
  # Fedora
  ##########################################################################
  - Fedora2[8-9]:
    - python-futures
    - python2-filelock
    - python2-libselinux
    - python2-pam
    - python2-setuptools
    - python2-tzlocal

  # Common to all Fedora starting with Fedora28.
  - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
    - ack
    - dkms
    - fedora-repos-rawhide
    - grubby
    - koji
    - perl-Data-Compare
    - python-devel
    - python-psutil
    - python-pyyaml
    - python-six
    - python3-filelock
    - python3-libselinux
    - python3-PyYAML
    - python3-tzlocal
    - redhat-lsb-core
    - screen
    - sshfs

  # These packages are not available beginning with Fedora34
  - Fedora([1-9][0-9]{2,}|2[8-9]|3[0-3]):
    - ntp
    - xinetd

  - Fedora30:
    - python2-libselinux

  - Fedora3[0-1]:
    - python-futures
    - PyYAML

  # Common to all Fedora starting with Fedora30.
  - Fedora([1-9][0-9]{2,}|3[0-9]|[4-9][0-9]):
    - python-pam
    - python-setuptools

  # Common to all Fedora starting with Fedora31.
  - Fedora([1-9][0-9]{2,}|3[1-9]|[4-9][0-9]):
    - device-mapper-devel

  # Common to all Fedora starting with Fedora32.
  - Fedora([1-9][0-9]{2,}|3[2-9]|[4-9][0-9]):
    - python27

  # Common to all Fedora starting with Fedora35.
  - Fedora([1-9][0-9]{2,}|3[5-9]|[4-9][0-9]):
    - python3-pbit-lsb-release

  ##########################################################################
  # RHEL families
  ##########################################################################
  - (CentOS|RedHat)7\.[5-6]:
    # EPEL offers us Python 3.4 but a PyYAML that is packaged for Python
    # 3.6.
    - python34

  - (CentOS|RedHat)7\.[7-9]:
    - python3
    - python36-PyYAML

  # Common to all RHEL 7 family starting with RHEL 7.5 family.
  - (CentOS|RedHat)7\.([1-9][0-9]+|[5-9]):
    - libselinux-python
    - ntp
    - python-devel
    - python-filelock
    - python-futures
    - python-pam
    - python-psutil
    - python-setuptools
    - python-six
    - python-tzlocal
    - PyYAML

  # Common to all RHEL families starting with RHEL 7.5 family.
  - (CentOS|RedHat)([1-9][0-9]+\.[0-9]+|([7-9])\.([1-9][0-9]+)|7\.[5-9]|[8-9]\.[0-9]):
    - dkms

  # Common to all RHEL 7.5 and 8 families
  - (CentOS|RedHat)((8\.([1-9][0-9]+|[0-9]))|(7\.(([1-9][0-9]+|[5-9])))):
    - perl-Data-Compare
    - redhat-lsb-core
    - screen
    - sshfs
    - xinetd

  - (CentOS|RedHat)8\.0:
    - python3-filelock

  # Common to all RHEL families starting with RHEL 8.0 family.
  - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
    - gcc
    - python3
    - python3-devel
    - python3-libselinux
    - python3-pyyaml
    - python3-setuptools
    - python3-six
    - python3-pyyaml

  # Common to all RHEL families starting with RHEL 8.6 family.
  - (CentOS|RedHat)(?![1-7]\.[0-9]+|8\.[0-5]$)[1-9][0-9]*\.[0-9]+:
    - python3-pbit-lsb-release

  # Common to all RHEL families starting with RHEL 9 family.
  - (CentOS|RedHat)(([1-9][0-9]+|9)\.([1-9][0-9]+|[0-9])):
    - glibc-langpack-en
    - s-nail

  ##########################################################################
  # Environment-specific.
  ##########################################################################
  - environment:
    - python2:
      # Common to all RHEL families starting with RHEL 8.0 family.
      - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
        - python2
        - python2-devel
        - python2-numpy
        - python2-pyyaml
        - python2-setuptools
        - python2-six

  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
    - ppc64le:
    - s390x:
    - x86_64:

packages: "{{ _packages | select_install(_base_selection) + extra_user_packages }}"

# Perl modules to install, either as RPMs or from CPAN.
# Modules with a cpan version specified are installed before any other
# modules.
#
# N.B. The modules are specified based on order dependence.
_perl_libraries:
  ##########################################################################
  # Architecture-specific.
  ##########################################################################
  - architecture:
    - aarch64:
    - ppc64le:
    - s390x:
      # Common to all RHEL 8 families through RHEL 8.5 family.
      - (CentOS|RedHat)8\.[0-5]$:
        # Clone (required by PPI) version 0.42 and later has a new dependency
        # on B::COW (which is at version 0.001, so there's nothing to roll back
        # to there) which doesn't install on RHEL8 for S390X.  So, we specify a
        # version of Clone prior to 0.42.
        - Clone~"< 0.42"
    - x86_64:

  ##########################################################################
  # Fedora
  ##########################################################################
  - Fedora28:
    - bignum

  # Common to all Fedora starting with Fedora28.
  - Fedora([1-9][0-9]{2,}|2[8-9]|[3-9][0-9]):
    - Test::Base

  ##########################################################################
  # RHEL families
  ##########################################################################
  # Common to all RHEL families starting with RHEL 8.0 family.
  - (CentOS|RedHat)(?![1-7]\.[0-9]+)[1-9][0-9]*\.[0-9]+:
    - HTTP::Daemon

  # Common to all RHEL families starting with RHEL 7.5 through RHEL 8.3.
  - (CentOS|RedHat)(7\.([1-9][0-9]+|[5-9])|8\.[0-3](?![0-9])):
    # Historically we encountered PPI conflicts with Perl::Critic tests.
    # At least as of RHEL 8.4 this is no longer the case.
    # As RHEL 8.4 is the current (11/01/2021) oldest version we're actively
    # using we specify a version of PPI before those conflicts were introduced
    # for releases prior to RHEL 8.4.
    #
    # PPI's dependency IO::String doesn't install cleanly on Fedora 28 for some
    # reason, so we add this only for systems where Perl::Critic isn't packaged
    # as an RPM.
    - PPI~"< 1.248"

  # Common to all RHEL 7 family starting with RHEL 7.5 family.
  - (CentOS|RedHat)7\.([1-9][0-9]+|[5-9]):
    # Test::More is needed first.
    - Test::More
    - Env
    - File::HomeDir
    - Log::Dispatch::FileRotate
    - Pod::Spell

  # Common to all RHEL families starting with RHEL 9 family.
  - (CentOS|RedHat)(([1-9][0-9]+|9)\.([1-9][0-9]+|[0-9])):
    - Data::Compare

  ##########################################################################
  # Common to all distributions.
  ##########################################################################
  - common:
    - BSD::Resource
    - Class::Inner
    - DBD::Pg
    - DBD::SQLite
    - Date::Calc
    - Date::Manip
    - Devel::Symdump
    - File::NFSLock
    - File::Slurp
    - File::chdir
    - JSON
    - List::Compare
    - List::MoreUtils
    - Log::Dispatch
    - Log::Log4perl
    - LWP::Protocol::https
    - MailTools
    - Params::Validate
    - Parse::Debian::Packages
    - Parse::RecDescent
    - Perl::Critic
    - Perl::Critic::More
    - Perl::Critic::Policy::Miscellanea::RequireRcsKeywords
    - Proc::ProcessTable
    - Regexp::Common
    - SOAP::Lite
    - Statistics::Descriptive
    - String::ShellQuote
    - Sys::CPU
    - Test::Unit::Lite
    - Tie::IxHash
    - Time::Duration
    - XML::Generator
    - XML::XPath
    - YAML
    - autodie

perl_libraries: "{{ _perl_libraries | select_install(_base_selection) }}"
