---
- name: Register with the RSVP server
  vars:
    arch_class: "{{ ansible_architecture | upper }}"
    farm: "{{ inventory_hostname }}"
    os_class: "
      {%- set distribution = ansible_distribution | upper -%}
      {%- if distribution == 'REDHAT' -%}
        RHEL{{ ansible_distribution_major_version }}
      {%- else -%}
        {{ distribution }}{{ ansible_distribution_major_version }}
      {%- endif -%}"
    classes:
      - ALBIREO
      - ALL
      - FARM
      - VDO
      - VFARM
      - "{{ os_class }}"
      - "{{ arch_class }}"
      - "{{ is_fedora | bool | ternary('FEDORA', omit) }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_family | bool))
            | ternary('LINUX-UDS', omit) }}"
      - "{{ ((is_fedora | bool) or (is_rhel8_family | bool))
            | ternary('LINUX-VDO', omit) }}"
      - "{{ is_performance_farm | ternary('VDO-PMI', omit) }}"
    # For convenience above, we want to support something like the "omit"
    # construct, but it doesn't work in simple list contexts; "omit" just
    # expands to some magic cookie value which we still have to explicitly
    # filter out.
    class_list: "{{ classes | difference(omit) | join(',') }}"
  command: "rsvpclient --dhost {{ rsvp_server }} add {{ farm }} \
            --classes {{ class_list }}"
  become: yes
  become_user: "{{ bunsen_user }}"
  register: result
  failed_when:
    - result.rc != 0
    - not (result.stderr is search(inventory_hostname ~ '.* already exists'))
    - not (result.stderr is search(hostvars[inventory_hostname].ansible_fqdn ~ '.* already exists'))
  changed_when: result.rc == 0

  # TODO: get the classes from the server.
  #       The list_classes --csv output is as:
  #         ALL,Default Class,class
  #         FARM,Default reservation class,class
  #         RHEL7, ,class
  #         VDO, ,class
  #         VFARM, ,class


